# Generated by Django 2.1.3 on 2018-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('rg', models.IntegerField(max_length=7)),
                ('cpf', models.IntegerField(max_length=11)),
                ('cep', models.IntegerField(max_length=8)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(max_length=10)),
                ('celular', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('cep', models.IntegerField(max_length=8)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(max_length=10)),
                ('celular', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
